### ISSUE TITLE
Publish v6.2 to CPAN

### ISSUE THREAD

**Issue by bombsimon** [simonwistow/Module-Pluggable#26]
Hi! Thanks for maintaining this module!

I noticed in [one of my pipelines](https://github.com/personnummer/perl/pull/91) a regression from the v6.1 release. After som digging I saw that 6.1 was published but that you shortly after created a [new tag for 6.2](https://github.com/simonwistow/Module-Pluggable/commit/e9b105ca961c9c4317a649a46fa9ac0b4734d623) here on GitHub.

So my first question, are you planning to release this new tag and version to CPAN? It seems like I still can't install `Module::Pluggable` since I'm lacking `File::Slurp`. Surely I can just install that dependency manually but would  be nice if I didn't have to. Or am I doing something wrong here trying to install the module?

Secondly I'm curious about where these commits that aren't a part of this repo happens that your tags are based on? Same for the 6.1 tag which added a bunch of new changes that's not to be seen on the main branch of this repo?

**Comment by michael-cr41g** [comment]
worked around this with `cpanm --force`; my understanding is the failure was caused by a missing dependency that shouldn't have existed in the first place so forcing the install without it is fine. though i'm not sure you'd want this as a long term solution

**Comment by simonwistow** [comment]
Sorry, my workflow script somehow managed to get messed up and I didn't notice because I was tired :(

Everything should be pushed to main, the tag should be properly published and 6.2 should be on its way to CPAN as we speak.

Sorry about the confusion.

**Comment by bombsimon** [comment]
> worked around this with `cpanm --force`; my understanding is the failure was caused by a missing dependency that shouldn't have existed in the first place so forcing the install without it is fine. though i'm not sure you'd want this as a long term solution

Yes exactly. And since it was just in a test `--notest` would also work. But yeah, wanted to flag for a long term fix.

> Sorry, my workflow script somehow managed to get messed up and I didn't notice because I was tired :(
> 
> Everything should be pushed to main, the tag should be properly published and 6.2 should be on its way to CPAN as we speak.
> 
> Sorry about the confusion.

No worries! Everything works as expected now, thanks for a quick fix!
